import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased max-h-full`}
      >
        <header className="min-h-[70px]  bg-purple-100 fixed w-full z-10 flex justify-center items-center">
            <h1 className="font-extrabold text-3xl">The Pkimon Explorer</h1>
        </header>
        <main className=" bg-purple-100">
        {children}
        </main>
        <footer className="min-h-[50px] bg-slate-500 text-center flex items-center justify-center">
            Thank you all
        </footer>
      </body>
    </html>
  );
}
